# Site settings
title: Bobby's Code Blog
header-img: img/moraine.jpg
email: beauxespirit@gmail.com
copyright_name: Bobby's Code Blog
description: "Mostly about code. "
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: beauxespirits
github_username:  hobertro
facebook_username:
email_username:  beauxespirit@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-merlot