# Site settings
title: Whipster Code Blog
header-img: img/home-bg.jpg
email: beauxespirit@gmail.com
copyright_name: The Whipster Code Blog
description: "Mostly about code. "
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: beauxespirits
github_username:  djshrek
facebook_username:  robert.ho
email_username:  beauxespirit@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
